
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Привет мир!");
            Console.WriteLine("Введите вашу фамилию:");
            string lastName = Console.ReadLine();
            Console.WriteLine("Ваша фамилия: " + lastName);
            Console.WriteLine("Введите ваш возраст:");
            int age = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Ваш возраст: " + age);
